name: Terraform Plan

on:
  push:
    branches:
      - '**'  # Triggers on all branches

jobs:
  terraform-plan:
    # Ensures the workflow can use GitHub Actions marketplace and, if needed,
    # authenticate with OIDC for GCP. (contents: read, id-token: write)
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'  # Adjust to your desired version

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          # If you're using a GCP keyfile, set this secret in your repo settings
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Show Terraform Plan
        run: terraform show tfplan

      - name: Upload Plan as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
